version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jobmanager:
    build: 
      context: .
      dockerfile: myflink.dockerfile
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 1
        python.client.executable: python3
    volumes:
      - ./flink_consumer.py:/opt/flink/usrlib/flink_consumer.py
      - ./requirements.txt:/opt/flink/requirements.txt
      - ./nltk_data:/opt/flink/nltk_data
      - ./flink_output:/tmp/flink_output
      - ./reddit_sentiment_collector.py:/opt/flink/usrlib/reddit_sentiment_collector.py

  taskmanager:
    build:
      context: .
      dockerfile: myflink.dockerfile
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 1728m
        taskmanager.memory.flink.size: 1280m
        python.client.executable: python3
    volumes:
      - ./flink_consumer.py:/opt/flink/usrlib/flink_consumer.py
      - ./requirements.txt:/opt/flink/requirements.txt
      - ./nltk_data:/opt/flink/nltk_data
      - ./flink_output:/tmp/flink_output
      - ./reddit_sentiment_collector.py:/opt/flink/usrlib/reddit_sentiment_collector.py
    networks:
      - default

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
